version: '3'
services:
  db:
    container_name: massagedb
    image: mongo:latest
    command: mongod --quiet --logpath /dev/null 
    ports:
      - 27017:27017

    restart: unless-stopped
    
    volumes:
      - ./mongo:/data/db
  
  massagebot:
    container_name: massageBot
    build: .
    depends_on:
      - db
