version: '3'
services:
  db:
    container_name: massageDb
    
    image: mongo:latest
    command: mongod --quiet --logpath /dev/null 
    ports:
      - 27017:27017

    environment:
      MONGO_INITDB_ROOT_USERNAME: gk42fiuvxdalkh
      MONGO_INITDB_ROOT_PASSWORD: bupoiq3HblSDA1

    restart: unless-stopped
    
    volumes:
      - ./mongodb:/data/db
  
  massagebot:
    container_name: massageBot
    build: .
    depends_on:
      - db
